apiVersion: v1
kind: Service
metadata:
  name: spotify-app
  labels:
    app: spotify-app
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 3000
  selector:
    app: spotify-app